theme: congo
defaultContentLanguage: en
enableRobotsTXT: true
summaryLength: 0
pagination:
  pagerSize: 10
outputs:
  home:
    - HTML
    - RSS
    - JSON
privacy:
  vimeo:
    enableDNT: true
  x:
    enableDNT: true
  youTube:
    privacyEnhanced: true
services:
  x:
    disableInlineCSS: true
